### ISSUE TITLE
api error

### ISSUE THREAD

**Issue by hweining** [mangix/nbalive#5]
loading game info..
Error: api error
    at Request._callback (/usr/local/lib/node_modules/nbalive/lib/remote/api.js:37:21)
    at Request.self.callback (/usr/local/lib/node_modules/nbalive/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/nbalive/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/nbalive/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by hweining** [comment]
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
WARN notice [SECURITY] lodash has the following vulnerability: 1 low.
